services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  FriendsOfTYPO3\DeferredImageProcessing\:
    resource: '../Classes/*'

  FriendsOfTYPO3\DeferredImageProcessing\Resource\Processing\DeferredFrontendImageProcessor:
    public: true
